[[Qt6ShaderTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f18b3215689bcecb5eb8edbbc48d2039e4a51e4"
libc = "musl"
os = "linux"

    [[Qt6ShaderTools.download]]
    sha256 = "5d07ada4121dce57a40e8352b6b30f7e3e83e90d382ef06aa56a70cc72d23ef4"
    url = "https://github.com/barche/Qt6ShaderTools_jll.jl/releases/download/Qt6ShaderTools-v6.3.0+0/Qt6ShaderTools.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6ShaderTools]]
arch = "x86_64"
git-tree-sha1 = "1abbf7db45bc7d662ca8cc5ebe0df6cef9640d9d"
os = "macos"

    [[Qt6ShaderTools.download]]
    sha256 = "3395f5fd2918eec306e5ac38cece8c33335060cb8b04219b66b81b8fbe4a7343"
    url = "https://github.com/barche/Qt6ShaderTools_jll.jl/releases/download/Qt6ShaderTools-v6.3.0+1/Qt6ShaderTools.v6.3.0.x86_64-apple-darwin.tar.gz"
[[Qt6ShaderTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aed17cc75a22c3578a46d94697991e2629bab613"
libc = "glibc"
os = "linux"

    [[Qt6ShaderTools.download]]
    sha256 = "951ff92665209e977f801f65ef043a8843a4471e04fabb4aa5235ef126c06419"
    url = "https://github.com/barche/Qt6ShaderTools_jll.jl/releases/download/Qt6ShaderTools-v6.3.0+1/Qt6ShaderTools.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
