# Autogenerated wrapper script for Qt6ShaderTools_jll for x86_64-linux-musl-cxx11
export qsb

using Qt6Base_jll
JLLWrappers.@generate_wrapper_header("Qt6ShaderTools")
JLLWrappers.@declare_executable_product(qsb)
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll)
    JLLWrappers.@init_executable_product(
        qsb,
        "bin/qsb",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
